version: "3"

services:
  dev-proxy:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: dev-proxy
    ports:
      - "9997:22"
    environment:
      - VIRTUAL_HOST={DOMAIN}
      - LETSENCRYPT_HOST={DOMAIN}
    networks:
      service_network:
networks:
  service_network:
    external: true
